branch-defaults:
  develop:
    environment: # elastic beanstalk environment namve
  main:
    environment: # elastic beanstalk environment namve

global:
  application_name: # elastic beanstalk application name
  branch: null
  default_ec2_keyname: # EC2 keypair
  default_platform: # docker platform
  default_region: # elastic beanstalk region
  include_git_submodules: true # ??
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application