# Generated by Django 3.0 on 2021-07-08 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(blank=True, help_text='성', max_length=31)),
                ('first_name', models.CharField(blank=True, help_text='이름', max_length=31)),
                ('phone_number', models.CharField(blank=True, help_text='핸드폰 번호', max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ON_SIGNUP', '가입 중'), ('PROFILE_CREATED', '프로필 생성 완료'), ('IDENTITY_AUTHENTICATED', '본인인증 완료'), ('WITHDRAWAL', '탈퇴'), ('SUSPENDED', '이용 정지')], default='ON_SIGNUP', help_text='유저 가입 상태', max_length=31)),
                ('user', models.OneToOneField(help_text='유저', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
